version: "3"

dotenv:
  - .env

tasks:
  test-main:
    cmds:
      - go test -v . -run TestMain
    silent: true
  bufgen:
    dir: _test/proto
    cmd: buf generate
  bufdeps:
    dir: _test/proto
    cmd: buf dep update
  sqlc:
    cmd: sqlc generate
    dir: _test
